name: firebase_database_mocks

description: Mock Library to write unit tests for FirebaseDatabase (real-time database).

version: 0.8.0

repository: https://github.com/sitatec/firebase_database_mocks.git
homepage: https://github.com/sitatec/firebase_database_mocks.git
issue_tracker: https://github.com/sitatec/firebase_database_mocks/issues

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  firebase_database: ^11.3.9
  mockito: ^5.4.6
  firebase_core_platform_interface: ^6.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
